[versions]
agp = "8.3.1"
androidxConstraintlayout = "2.0.4"
compiler = "4.12.0"
compilerVersion = "4.13.0"
constraintlayoutVersion = "2.2.1"
core = "3.4.0"
espressoCoreVersion = "3.6.1"
githubCompiler = "4.7.1"
glide = "4.13.0"
googleMaterial = "1.4.0"
gson = "2.10.1"
json = "20210307"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
kotlin = "1.9.0"
materialVersion = "1.12.0"
navigationCompose = "2.9.0"
okhttp = "4.9.0"
picasso = "2.71828"
playServicesMapsVersion = "19.2.0"
volley = "1.2.1"
zxingAndroidEmbedded = "4.1.0"

[libraries]
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
compiler-v4130 = { module = "com.github.bumptech.glide:compiler", version.ref = "compilerVersion" }
compiler-v471 = { module = "com.github.bumptech.glide:compiler", version.ref = "githubCompiler" }
constraintlayout-v204 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
constraintlayout-v221 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
core = { module = "com.google.zxing:core", version.ref = "core" }
espresso-core-v361 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
gms-play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMapsVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
json = { module = "org.json:json", version.ref = "json" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material-v140 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
volley = { module = "com.android.volley:volley", version.ref = "volley" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

